name: Build & Publish Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/trackit

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore
        run: dotnet restore TrackIt.csproj

      - name: Build
        run: dotnet build TrackIt.csproj -c Release --no-restore

      - name: Publish (framework-dependent)
        run: dotnet publish TrackIt.csproj -c Release -o publish --no-build

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: vars
        run: |
          VERSION=$(date +"%Y.%m.%d-%H%M%S")
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build image
        run: |
          docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ steps.vars.outputs.version }} .

      - name: Push image
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ steps.vars.outputs.version }}

      - name: Summary
        run: |
          echo "Image pushed: $IMAGE_NAME:latest" >> $GITHUB_STEP_SUMMARY
          echo "Tagged: $IMAGE_NAME:${{ steps.vars.outputs.version }}" >> $GITHUB_STEP_SUMMARY
